
const products = [
    {
        id: 1,
        title: 'Lavender Dreams',
        price: '$5.99',
        rating: 4,
        tag: 'Moisturizing',
        desc: 'Gentle lavender with nourishing oils.',
        image: 'https://images.unsplash.com/photo-1552046122-03184de85e08?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        category: "Aromatherapy",
        scent: "Lavender",
        ingredients: ["Olive Oil", "Coconut Oil", "Lavender Essential Oil", "Dried Lavender"],
        featured: true,
    },
    {
        id: 2,
        title: 'Honey Oat Bliss',
        price: '$6.49',
        rating: 5,
        tag: 'Soothing',
        desc: 'Perfect for dry, sensitive skin.',
        image: 'https://images.unsplash.com/photo-1552046122-03184de85e08?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        category: "Exfoliating",
        scent: "Honey",
        ingredients: ["Oatmeal", "Raw Honey", "Shea Butter", "Goat Milk"],
        featured: true,
    },
    {
        id: 3,
        title: 'Rose Garden',
        price: '$6.99',
        rating: 4,
        tag: 'Aromatic',
        desc: 'Delicate rose scent with shea butter.',
        image: 'https://images.unsplash.com/photo-1552046122-03184de85e08?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        category: "Moisturizing",
        scent: "Rose",
        ingredients: ["Rose Petals", "Shea Butter", "Rose Essential Oil", "Vitamin E"],
        featured: true,
    },
    {
        id: 4,
        title: 'Charcoal Detox',
        price: '$6.25',
        rating: 4,
        tag: 'Purifying',
        desc: 'Draws out impurities and clarifies.',
        image: 'https://images.unsplash.com/photo-1552046122-03184de85e08?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        category: "Exfoliating",
        scent: "Unscented",
        ingredients: ["Activated Charcoal", "Tea Tree Oil", "Coconut Oil", "Clay"],
        featured: false,
    },
    {
        id: 5,
        title: 'Vanilla Coconut',
        price: '$5.75',
        rating: 5,
        tag: 'Hydrating',
        desc: 'Warm, creamy scent with deep moisture.',
        image: 'https://images.unsplash.com/photo-1552046122-03184de85e08?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        category: "Moisturizing",
        scent: "Vanilla & Coconut",
        ingredients: ["Coconut Oil", "Vanilla Extract", "Cocoa Butter", "Sweet Almond Oil"],
        featured: false,
    },
    {
        id: 6,
        title: 'Citrus Sunrise',
        price: '$5.50',
        rating: 4,
        tag: 'Energizing',
        desc: 'Zesty citrus scent to start your day.',
        image: 'https://images.unsplash.com/photo-1552046122-03184de85e08?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        category: "Refreshing",
        scent: "Citrus",
        ingredients: ["Orange Peel", "Lemon Essential Oil", "Coconut Oil", "Olive Oil"],
        featured: true,
    },
    {
        id: 7,
        title: 'Minty Fresh',
        price: '$5.99',
        rating: 5,
        tag: 'Refreshing',
        desc: 'Cool mint for a crisp, clean feel.',
        image: 'https://images.unsplash.com/photo-1552046122-03184de85e08?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        category: "Refreshing",
        scent: "Mint",
        ingredients: ["Peppermint Essential Oil", "Shea Butter", "Coconut Oil", "Olive Oil"],
        featured: true,
    },
    {
        id: 8,
        title: 'Almond Milk Calm',
        price: '$6.29',
        rating: 4,
        tag: 'Gentle',
        desc: 'Soothes and calms irritated skin.',
        image: 'https://images.unsplash.com/photo-1552046122-03184de85e08?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        category: "Moisturizing",
        scent: "Almond",
        ingredients: ["Almond Milk", "Coconut Oil", "Shea Butter", "Oat Extract"],
        featured: true,
    },
    {
        id: 9,
        title: 'Coffee Scrub Wakeup',
        price: '$6.95',
        rating: 5,
        tag: 'Exfoliating',
        desc: 'Gently exfoliates and invigorates.',
        image: 'https://images.unsplash.com/photo-1552046122-03184de85e08?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        category: "Exfoliating",
        scent: "Coffee",
        ingredients: ["Ground Coffee", "Cocoa Butter", "Coconut Oil", "Shea Butter"],
        featured: true,
    },
    {
        id: 10,
        title: 'Aloe Vera Calm',
        price: '$5.45',
        rating: 4,
        tag: 'Cooling',
        desc: 'Aloe-rich soap perfect for sun-kissed skin.',
        image: 'https://images.unsplash.com/photo-1552046122-03184de85e08?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        category: "Soothing",
        scent: "Aloe Vera",
        ingredients: ["Aloe Vera Gel", "Shea Butter", "Coconut Oil", "Vitamin E"],
        featured: true,
    },
    {
        id: 11,
        title: "Tea Tree Fresh",
        price: "$11.99",
        rating: 5,
        tag: "Antibacterial",
        desc: "Antibacterial tea tree oil soap perfect for problem skin and acne treatment.",
        image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
        category: "Sensitive Skin",
        scent: "Tea Tree",
        ingredients: ["Tea Tree Oil", "Aloe Vera", "Chamomile", "Calendula"],
        featured: false,
    },
    {
        id: 12,
        title: "Shea Butter Cream",
        price: "$18.99",
        rating: 5,
        tag: "Moisturizing",
        desc: "Ultra moisturizing shea butter soap for dry and sensitive skin types.",
        image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
        category: "Moisturizing",
        scent: "Unscented",
        ingredients: ["Raw Shea Butter", "Argan Oil", "Vitamin E", "Jojoba Oil"],
        featured: false,
    },


];

export default products;